name: Build XAMPP Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libtool pkg-config

      - name: Install dependencies
        run: |
          sudo apt-get install -y wget unzip
          wget https://apachefriends.org/xampp-files/xampp-linux-x64-7.4.4-0-installer.run
          chmod +x xampp-linux-x64-7.4.4-0-installer.run
          sudo ./xampp-linux-x64-7.4.4-0-installer.run

      - name: Build XAMPP Installer
        run: |
          cd /path/to/xampp-build
          ./build-xampp.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xampp-installer
          path: /path/to/xampp-build/output/installer.exe
